import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Input from "@/components/Input/Input";
import { useEffect, useState } from "react";
import ItemList from "@/components/ItemList/ItemList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [itemList, setItemList] = useState<string[]>([]);
  const [toggled, setToggled] = useState(false);

  const toggle: any = () => {
    toggled ? setToggled(false) : setToggled(true);
  };
  const addItem: any = (item: string) => {
    setItemList([...itemList, item]);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        isToggle={() => {
          toggle();
        }}
      />
      {toggled ? (
        <Input
          addItem={(item: string) => addItem(item)}
          isToggle={() => toggle()}
        />
      ) : (
        ""
      )}
      <ItemList itemList={itemList} />
    </>
  );
}
